# Generated by Django 5.1.1 on 2024-09-11 16:18

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_id', models.IntegerField()),
                ('admin_name', models.CharField(max_length=50)),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('password', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'admin',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.IntegerField()),
                ('emp_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=100)),
                ('pic', models.ImageField(upload_to='employee/')),
                ('password', models.CharField(max_length=100)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_admin.admin')),
            ],
            options={
                'db_table': 'staff',
            },
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('added_date', models.DateTimeField(default=django.utils.timezone.now, null=True)),
                ('pic', models.ImageField(upload_to='job/')),
                ('status', models.CharField(default='pending', max_length=100)),
                ('added_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_admin.admin')),
            ],
            options={
                'db_table': 'job',
            },
        ),
        migrations.CreateModel(
            name='JobAssignee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateTimeField(null=True)),
                ('status', models.CharField(default='pending', max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_admin.employee')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='job_admin.job')),
            ],
            options={
                'db_table': 'job_assignee',
            },
        ),
    ]
